openapi: 3.1.0
info:
  title: BPDP-SEMAI API
  version: 1.0.0
  description: |
    API untuk pertukaran data antara sistem BPDP dan SEMAI, mencakup manajemen file dan tarif pungutan.

servers:
  - url: https://api.example.com/v1

paths:
  /files/generate:
    post:
      summary: Upload file dan generate data dari BPDP ke SEMAI
      operationId: bpdpToSemaiGenerateFile
      requestBody:
        description: Payload untuk request file dari BPDP ke SEMAI
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BPDPToSemaiFileRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

  /files/submit:
    post:
      summary: Submit data yang telah diproses dari SEMAI ke BPDP
      operationId: semaiToBpdpSubmitFile
      requestBody:
        description: Payload untuk submit data hasil pemrosesan file dari SEMAI ke BPDP
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SemaiToBpdpFileRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

  /tariffs:
    post:
      summary: Mendokumentasikan tarif pungutan dari BPDP ke SEMAI
      operationId: bpdpToSemaiTariff
      requestBody:
        description: Request untuk tarif pungutan dari BPDP ke SEMAI
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BPDPToSemaiTariffRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

  /tariffs/update:
    post:
      summary: Mengirimkan pembaruan tarif pungutan dari SEMAI ke BPDP
      operationId: semaiToBpdpTariffUpdate
      requestBody:
        description: Request untuk pembaruan tarif pungutan dari SEMAI ke BPDP
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SemaiToBpdpTariffRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

components:
  schemas:
    DefaultResponse:
      type: object
      properties:
        status:
          type: integer
          description: Kode status HTTP
          example: 200
        message:
          type: string
          description: Pesan status response
          example: success
        data:
          type: object
          description: Optional data payload
          nullable: true

    BPDPToSemaiFileRequest:
      type: object
      required:
        - file_id
        - file_url
        - category
        - request_id
      properties:
        file_id:
          type: integer
          description: ID file upload di database
          example: 1
        file_url:
          type: string
          format: uri
          description: URL untuk mengakses file
          example: "https://example.com/storage/uploads/rekening-koran/evidence/file.xlsx"
        category:
          type: string
          description: Kategori file upload
          example: "rekening_koran"
          enum: [rekening_koran, master_hpe, keberatan_sp3es, restitusi]
        request_id:
          type: string
          format: uuid
          description: UUID dari BPDP
          example: "01f2e3a4-b5c6-d7e8-f9a0-112233445566"

    SemaiToBpdpFileRequest:
      type: object
      required:
        - file_id
        - request_id
        - category
        - rows
      properties:
        file_id:
          type: integer
          description: ID file upload di database SEMAI
          example: 123
        request_id:
          type: string
          format: uuid
          description: UUID dari SEMAI
          example: "01f2e3a4-b5c6-d7e8-f9a0-112233445566"
        category:
          type: string
          description: Kategori file upload
          example: "rekening_koran"
          enum: [rekening_koran, kepmendag_merk]
        row_count:
          type: integer
          description: Jumlah baris data, khusus untuk bulk insert
          example: 20
        rows:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/RekeningKoranData'
              - $ref: '#/components/schemas/KepmendagMerkData'
          description: Isi data dalam bentuk array

    RekeningKoranData:
      type: object
      properties:
        tanggal_transaksi:
          type: string
          format: date
          example: "2025-01-01"
        bank:
          type: string
          example: "BCA"
        kode_billing:
          type: string
          example: "1234567890"
        jumlah_pungutan:
          type: number
          format: float
          example: 100000.00
    
    KepmendagMerkData:
      type: object
      properties:
        nama_merek:
          type: string
          example: "AFRICA SUPER OLIO"
        pemilik_merek:
          type: string
          example: "PT. Berkah Emas Sumber Terang"
        pemroduksi_merek:
          type: string
          example: "PT. Royal Industries Indonesia"
        nomor_keputusan:
          type: string
          example: "NOMOR 2018 TAHUN 2023"

    BPDPToSemaiTariffRequest:
      type: object
      required:
        - request_id
        - category
      properties:
        request_id:
          type: string
          format: uuid
          description: UUID dari BPDP
          example: "01f2e3a4-b5c6-d7e8-f9a0-112233445566"
        category:
          type: string
          description: Kategori permintaan
          example: "tarif_pungutan"
        uraian_lhp:
          type: string
          description: Uraian laporan hasil pemeriksaan
        tarif_pungutan:
          type: string
          description: Tarif pungutan dalam format string

    SemaiToBpdpTariffRequest:
      type: object
      required:
        - request_id
        - category
      properties:
        request_id:
          type: string
          format: uuid
          description: UUID dari SEMAI
          example: "01f2e3a4-b5c6-d7e8-f9a0-112233445566"
        category:
          type: string
          description: Kategori permintaan
          example: "tarif_pungutan"
        kelompok_tarif:
          type: string
          description: Kelompok tarif (dipisahkan koma)
          example: "I,II,III"
        nilai_tarif:
          type: string
          description: Nilai tarif (dipisahkan koma)
          example: "20,7.5,5"
        satuan_nilai_tarif:
          type: string
          description: Satuan dari nilai tarif
          example: "percent,usd"