openapi: 3.1.0
info:
  title: API Generate Files
  version: 1.0.0
  description: >
    API untuk mengirimkan informasi file dari SUCOFINDO ke SEMAI.
    Menerima metadata file dan mengembalikan status proses.

paths:
  /generate-files:
    post:
      summary: Mengirim data file dari SUCOFINDO ke SEMAI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: integer
                  description: ID file upload di database
                  example: 1
                file_url:
                  type: string
                  format: uri
                  description: URL untuk mengakses file
                  example: "https://example.com/storage/uploads/rekening-koran/evidence/file.xlsx"
                category:
                  type: string
                  description: >
                    Kategori file upload.
                    Contoh: rekening_koran, master_hpe, keberatan_sp3es, restitusi
                  example: "rekening_koran"
                request_id:
                  type: string
                  format: uuid
                  description: UUID dari SUCOFINDO
                  example: "a12f6b1e-4d98-4b22-bc41-2f6b9c3e8e9f"
              required:
                - file_id
                - file_url
                - category
                - request_id
      responses:
        "200":
          description: Request berhasil diproses
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    description: Data tambahan jika ada
        "403":
          description: Akses ditolak
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 403
                  message:
                    type: string
                    example: forbidden
